name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Secrets load step pehle
      - name: Setup Environment Variables
        run: |
          echo "RAZORPAY_KEY=${{ secrets.RAZORPAY_KEY }}" >> $GITHUB_ENV
          echo "RAZORPAY_SECRET=${{ secrets.RAZORPAY_SECRET }}" >> $GITHUB_ENV
          echo "RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }}" >> $GITHUB_ENV
          echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: publish/
